-- Time-log integrity for the timer engine.
--
-- Generated by `prisma migrate diff`, plus two hand-written parts that the
-- Prisma schema DSL cannot express (marked "Hand-written"):
--   1. a backfill so existing NULL durations don't block SET NOT NULL;
--   2. CHECK constraints that make impossible durations unrepresentable.

-- Hand-written: backfill before SET NOT NULL. Running timers get 0; stopped
-- logs get their duration recomputed from the stored timestamps.
UPDATE "TimeLog"
SET "durationSeconds" = CASE
  WHEN "stoppedAt" IS NULL THEN 0
  ELSE floor(extract(epoch FROM ("stoppedAt" - "startedAt")))::integer
END
WHERE "durationSeconds" IS NULL;

-- DropForeignKey
ALTER TABLE "TimeLog" DROP CONSTRAINT "TimeLog_taskId_fkey";

-- DropIndex (covered by the leading column of the composite indexes)
DROP INDEX "TimeLog_taskId_idx";

-- DropIndex (covered by the leading column of the composite indexes)
DROP INDEX "TimeLog_userId_idx";

-- DropIndex (the active-timer lookup uses the partial unique index instead)
DROP INDEX "TimeLog_userId_stoppedAt_idx";

-- AlterTable
ALTER TABLE "TimeLog" ALTER COLUMN "durationSeconds" SET NOT NULL,
ALTER COLUMN "durationSeconds" SET DEFAULT 0;

-- CreateIndex
CREATE UNIQUE INDEX "Task_id_userId_key" ON "Task"("id", "userId");

-- AddForeignKey: a log's (taskId, userId) must match a task owned by that user,
-- so the database itself refuses a time log that crosses ownership.
ALTER TABLE "TimeLog" ADD CONSTRAINT "TimeLog_taskId_userId_fkey" FOREIGN KEY ("taskId", "userId") REFERENCES "Task"("id", "userId") ON DELETE CASCADE ON UPDATE CASCADE;

-- Hand-written: CHECK constraints.
ALTER TABLE "TimeLog" ADD CONSTRAINT "TimeLog_duration_non_negative"
  CHECK ("durationSeconds" >= 0);

ALTER TABLE "TimeLog" ADD CONSTRAINT "TimeLog_stopped_after_started"
  CHECK ("stoppedAt" IS NULL OR "stoppedAt" >= "startedAt");

-- A running timer records 0; a stopped one records exactly the whole seconds
-- between its timestamps, so a stored duration can never disagree with them.
ALTER TABLE "TimeLog" ADD CONSTRAINT "TimeLog_duration_matches_timestamps"
  CHECK (
    ("stoppedAt" IS NULL AND "durationSeconds" = 0)
    OR ("stoppedAt" IS NOT NULL
        AND "durationSeconds" = floor(extract(epoch FROM ("stoppedAt" - "startedAt"))))
  );
