-- Daily productivity summary support.
--
-- Generated by `prisma migrate diff`, plus hand-written parts (marked) that the
-- Prisma schema DSL cannot express: a backfill and a CHECK constraint.

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "completedAt" TIMESTAMPTZ;

-- Hand-written: backfill. Tasks completed before this column existed get their
-- last update time — the best record available of when they were completed.
UPDATE "Task" SET "completedAt" = "updatedAt" WHERE "status" = 'COMPLETED';

-- Hand-written: completedAt is set exactly when the task is COMPLETED.
ALTER TABLE "Task" ADD CONSTRAINT "Task_completed_at_matches_status"
  CHECK (("status" = 'COMPLETED') = ("completedAt" IS NOT NULL));

-- CreateIndex
CREATE INDEX "Task_userId_completedAt_idx" ON "Task"("userId", "completedAt");

-- CreateIndex
CREATE INDEX "TimeLog_userId_stoppedAt_idx" ON "TimeLog"("userId", "stoppedAt");
